### ISSUE TITLE
Error sendVerificationCode

### ISSUE THREAD

**Issue by siuloirges** [MrlolDev/poe.js#1]
> node index.js

file:///workspaces/poe.js/node_modules/quora-poe.js/dist/index.js:204
            let { data: { sendVerificationCode: { status }, }, } = await this.makeRequest({
                                                ^

TypeError: Cannot read properties of undefined (reading 'sendVerificationCode')
    at ChatBot.sendVerifCode (file:///workspaces/poe.js/node_modules/quora-poe.js/dist/index.js:204:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatBot.login (file:///workspaces/poe.js/node_modules/quora-poe.js/dist/index.js:46:24)
    at async ChatBot.start (file:///workspaces/poe.js/node_modules/quora-poe.js/dist/index.js:38:9)
    at async file:///workspaces/poe.js/index.js:8:3

Node.js v19.8.1

---

Error al intentar usar la libreria, siguiendo los pasos del README.md, no me funciona local, ni tampoco en los codespace de github
Version node: v19.8.1

codigo del index.js:

import Poe from 'quora-poe.js';

(async () => {

  const bot = new Poe();
  await bot.start();
  let conversation = [
    {
      role: 'user',
      content: 'My name is John',
    },
    {
      role: 'ai',
      content:
        'Hello John! How can I help you today? If you have any questions or need assistance, please feel free to ask.Hello John! How can I help you today? If you have any questions or need assistance, please feel free to ask.',
    },
  ];
  let answer = await bot.send(conversation, 'gpt-4');

  console.log(answer)
})();

**Comment by lazuee** [comment]
@siuloirges Try use this https://github.com/Cohee1207/SillyTavern/blob/dev/poe-client.js
It's working properly, and they always maintain it,.

If you're are planning making a discord bot with it, see this,.
https://github.com/lazuee/discord-bot/tree/main/src/classes/poe
https://github.com/lazuee/discord-bot/blob/main/src/commands/chatgpt.ts

**Comment by siuloirges** [comment]
@lazuee Muchas gracias por tu comentario!
Lo intentaré.

**Comment by lazuee** [comment]
@MrlolDev https://github.com/lazuee/poe.js
